### ISSUE TITLE
Avere per ogni quartiere area e abitanti

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/palermo-sinistri-2022#1]
Rendere disponibile questo dato, in modo da presentare i valori di insieme in modo più efficace

**Comment by gbvitrano** [comment]
![2023-10-13_15h26_44](https://github.com/opendatasicilia/palermo-sinistri-2022/assets/20488693/4474c510-6d43-40de-a30a-29cb5a0a663e)

da verificare...
la popolazione è il classico su 100.000 abitanti?

**Comment by aborruso** [comment]
> la popolazione è il classico su 100.000 abitanti?

Tu per ora rendi disponibile il file con i dati grezzi. E poi ci ragioniamo

**Comment by gbvitrano** [comment]
I dati sull popolazione residente 2022 per quartieri li ho presi dal [portale opendata](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1693) del comune, il file si trova anche nel repo [qui](https://github.com/opendatasicilia/palermo-sinistri-2022/blob/main/dati/csv/grezzi/residenti_quartieri.csv)
